manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: preceptorXS
      url-base: https://github.com/preceptorXS
  projects:
    - name: zmk
      remote: preceptorXS
      revision: main
      import: app/west.yml
  self:
    path: config
