manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jyojoh
      url-base: https://github.com/jyojoh
  projects:
    - name: zmk
      remote: jyojoh
      revision: main
      import: app/west.yml
  self:
    path: config
